# finetuning Llama-2-7b chat version on PileNER with N=5 samples per NE

base_model: meta-llama/Llama-2-7b-chat-hf
prompt_template_name: reverse_INST
# using dataset converted from MSEQA format to GenQA format (instruction, input, output) columns
data_path: ./datasets/pileNER/5_samples_per_NE_GenQA_TrueDef/train.jsonl
val_data_path: ./datasets/pileNER/5_samples_per_NE_GenQA_TrueDef/validation.jsonl
select_train_portion: -1
val_set_size: 500 # ca 1/4 of validation data
output_dir: ./trained_models/llama2_7B_5samplesPerNE_TrueDef
#training hyperparams
batch_size: 32
micro_batch_size: 1
num_epochs: 3
learning_rate: 3.0e-4
cutoff_len: 768

warmup_steps: 60
eval_steps: 20
logging_steps: 5
max_grad_norm: 1.0
#lora hyperparams
use_lora: True
lora_alpha: 16
lora_dropout: 0.05
lora_r: 8
lora_target_modules:
- q_proj
- v_proj
- k_proj
- v_proj
#llm hyperparams
# NTP loss only on Response
train_on_inputs: False
group_by_length: True
#quant params
load_8bit: False
load_4bit: False
#general param
save_total_limit: 2
use_flash_attention: False
shuffle: True
gradient_checkpointing: False